### ISSUE TITLE
Lets find a good tool to make our cli

### ISSUE THREAD

**Issue by jalwn** [Luthss/lite-search#1]
I propose we find a good tool for lite search. Lets try making a simple command line program using both nodejs and python. For the first tool test, the program should take in user input and give an output.

**Comment by Luthss** [comment]
Right

**Comment by Luthss** [comment]
I made some progress made hello world in Python and Javascript

**Comment by jalwn** [comment]
Good work. Try storing "Hello World" in a variable and use the variable in the print statement. Variables are useful for storing things in memory and being able to reference them later on.

**Comment by Luthss** [comment]
Done

**Comment by Luthss** [comment]
I have found ways to get user input before and after program execution

**Comment by Luthss** [comment]
I prefer we go ahead with python
